plugins {
    id "com.android.application"
}

android {
    namespace "com.dnio.gujarati.offline"
    compileSdk 35

    defaultConfig {
        applicationId "com.dnio.gujarati.offline"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError false
    }

    androidResources {
        noCompress += ["mp4"]
    }
}

dependencies {
    implementation "androidx.documentfile:documentfile:1.0.1"
}
