plugins {
    id "com.android.application"
}

android {
    namespace "com.dnio.gujarati.offline"
    compileSdk 35

    defaultConfig {
        applicationId "com.dnio.gujarati.offline"
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    androidResources {
        noCompress += ["mp4"]
    }
}
