const games=[
{id:1,title:'Sonic CD',subtitle:'Past. Present. Future.',platform:'cd',playtime:'2h 14m',hours:2.14,last:'Today',color:'#1677d2',accent:'#ffcf32',glyph:'S',favorite:true,saves:3},
{id:2,title:'Pokémon Emerald',subtitle:'The Hoenn adventure',platform:'gba',playtime:'18h 40m',hours:18.4,last:'Yesterday',color:'#1d9c62',accent:'#8ef0b0',glyph:'E',favorite:true,saves:5},
{id:3,title:'DOOM',subtitle:'Rip and tear',platform:'dos',playtime:'5h 02m',hours:5.02,last:'Jul 12',color:'#c43d2f',accent:'#ff9f38',glyph:'D',favorite:false,saves:2},
{id:4,title:'Wario Land 4',subtitle:'Treasure awaits',platform:'gba',playtime:'3h 21m',hours:3.21,last:'Jul 08',color:'#f1b91d',accent:'#ff6c8f',glyph:'W',favorite:false,saves:1},
{id:5,title:'Prince of Persia',subtitle:'The sands are moving',platform:'dos',playtime:'1h 05m',hours:1.05,last:'Jun 29',color:'#ed5a2a',accent:'#ffd777',glyph:'P',favorite:false,saves:1},
{id:6,title:'Myst',subtitle:'A world unlike any other',platform:'cd',playtime:'40m',hours:.4,last:'Jun 18',color:'#6659a7',accent:'#8ed5e8',glyph:'M',favorite:false,saves:0}];
const labels={dos:'DOS',gba:'GBA',cd:'CD-ROM'};let filter='all',query='',sort='recent';const favorites=new Set(games.filter(g=>g.favorite).map(g=>g.id));
const art=g=>`<div class="game-art" style="--cover:${g.color};--cover-accent:${g.accent}"><span class="art-grid"></span><span class="art-orbit"></span><span class="art-glyph">${g.glyph}</span><span class="art-title">${g.title}</span><span class="art-platform">${labels[g.platform]}</span></div>`;
function renderFilters(){const items=[['all',`All games ${games.length}`],['favorites',`★ Favorites ${favorites.size}`],['dos','DOS 2'],['gba','GBA 2'],['cd','CD-ROM 2']];document.querySelector('#filters').innerHTML=items.map(([v,l])=>`<button class="${filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('')}
function render(){renderFilters();let list=games.filter(g=>g.title.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='favorites'&&favorites.has(g.id)||g.platform===filter));if(sort==='az')list.sort((a,b)=>a.title.localeCompare(b.title));if(sort==='played')list.sort((a,b)=>b.hours-a.hours);document.querySelector('#grid').innerHTML=list.length?list.map((g,i)=>`<article class="game-card" style="animation-delay:${i*45}ms"><button class="favorite ${favorites.has(g.id)?'is-favorite':''}" data-favorite="${g.id}" aria-label="Toggle favourite">★</button><button class="game-open" data-open="${g.id}">${art(g)}<div class="game-info"><div><span class="platform platform-${g.platform}">${labels[g.platform]}</span><span class="last-played">${g.last}</span></div><h3>${g.title}</h3><p>${g.subtitle}</p><span class="playtime">◷ ${g.playtime} played</span></div></button><button class="quick-play" data-play="${g.id}">▶ PLAY</button></article>`).join(''):`<div class="empty"><span>?</span><h3>No game found</h3><p>Try another title or clear your filter.</p><button class="button secondary" data-action="home">Show all games</button></div>`}
function detail(g){document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><section class="detail-panel"><button class="modal-close" data-close>×</button><div class="detail-art">${art(g)}</div><div class="detail-copy"><button class="back-link" data-close>← BACK TO LIBRARY</button><span class="platform platform-${g.platform}">${labels[g.platform]}</span><h2>${g.title}</h2><p class="detail-subtitle">${g.subtitle}</p><div class="stats"><div><span>◷</span><span><small>PLAY TIME</small><strong>${g.playtime}</strong></span></div><div><span>▣</span><span><small>SAVE STATES</small><strong>${g.saves||'None yet'}</strong></span></div></div><div class="save-note"><span>✓</span><div><strong>Your progress is safe</strong><p>Auto-save runs when you exit the game.</p></div></div><button class="button launch" data-play="${g.id}">▶ LAUNCH GAME</button><p class="controller-hint">Press A to launch · B to go back</p></div></section></div>`}
function settings(){document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><section class="settings-panel"><div class="settings-title"><div><span class="section-kicker">SYSTEM</span><h2>Controller & saves</h2></div><button class="modal-close inline" data-close>×</button></div><div class="setting-row"><div><strong>Controller layout</strong><p>Choose the button map kids see.</p></div><select><option>SNES layout</option><option>Genesis layout</option><option>GBA layout</option></select></div>${[['Auto-save on exit','Keep progress without remembering to save.'],['Kid mode','Hide file tools and advanced settings.'],['Open ZIP games automatically','Extract to a temporary folder before play.']].map(x=>`<div class="setting-row"><div><strong>${x[0]}</strong><p>${x[1]}</p></div><button class="toggle on"><span></span></button></div>`).join('')}<div class="path-box"><span>BACKUP LOCATION</span><code>ARCADE_USB:/backups/</code><small>Last backup: today at 9:42 AM</small></div><button class="button launch" data-save>✓ SAVE SETTINGS</button></section></div>`}
function toast(text){const el=document.querySelector('#toast');el.innerHTML=`<div class="toast"><span>✓</span>${text}</div>`;setTimeout(()=>el.innerHTML='',2300)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;render()}if(b.dataset.favorite){const id=+b.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);render()}if(b.dataset.open)detail(games.find(g=>g.id==b.dataset.open));if(b.dataset.play){const g=games.find(g=>g.id==b.dataset.play);document.querySelector('#modal').innerHTML='';toast(`${g.title} is ready — have fun!`)}if(b.dataset.close!==undefined)document.querySelector('#modal').innerHTML='';if(b.dataset.action==='settings')settings();if(b.dataset.action==='home'){filter='all';query='';document.querySelector('#search').value='';render()}if(b.classList.contains('toggle'))b.classList.toggle('on');if(b.dataset.save!==undefined){document.querySelector('#modal').innerHTML='';toast('Settings saved')}});
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;render()});document.querySelector('#sort').addEventListener('change',e=>{sort=e.target.value;render()});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#modal').innerHTML='';if(e.key==='/'&&!document.querySelector('#modal').innerHTML){e.preventDefault();document.querySelector('#search').focus()}});render();
